include: package:very_good_analysis/analysis_options.5.1.0.yaml
linter:
  rules:
    public_member_api_docs: false
    sort_pub_dependencies: false
analyzer:
  errors:
    lines_longer_than_80_chars: ignore
    inference_failure_on_function_invocation: ignore
    inference_failure_on_function_return_type: ignore
    inference_failure_on_untyped_parameter: ignore
    avoid_dynamic_calls: ignore
    avoid_bool_literals_in_conditional_expressions: ignore
    avoid_positional_boolean_parameters: ignore
    unnecessary_lambdas: ignore
    one_member_abstracts: ignore